server:
  port: 8080

supabase:
  jwks-url: ${SUPABASE_JWKS_URL:https://jbpaivqemmarharbjbyv.supabase.co/auth/v1/keys}
  jwt-issuer: ${SUPABASE_JWT_ISSUER:https://jbpaivqemmarharbjbyv.supabase.co/auth/v1}
  jwt-secret: ${SUPABASE_JWT_SECRET:z95fJ4L21V0v69rHXd+lZwvdA2zfrWY7u+1SHwrJdz9cRqF51qHbMIPPQf9CeehVqgWvS5qThq7SvX/Vsrdexw==}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require}
    
    username: ${SPRING_DATASOURCE_USERNAME:postgres.jbpaivqemmarharbjbyv}
    
    password: ${SPRING_DATASOURCE_PASSWORD:QhKPb9VbpT2pBoMI}
    
    driver-class-name: org.postgresql.Driver
  jdbc:
    template:
      fetch-size: 100
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

logging:
  level:
    root: INFO